### ISSUE TITLE
Eclipse4.8で既存ER図保存できない

### ISSUE THREAD

**Issue by SUNNET-Tyou-Yu** [guoweihua1982/ermaster-g#5]
「カスタム型の追加」手順に従って、「3. 既存のER図に使ったカスタム型を変更する」を行い、保存すると、NullPointerExceptionが発生しました。
![保存時の例外](https://user-images.githubusercontent.com/46915434/70103985-055fa280-1680-11ea-8b5b-c852025593c0.png)

**Comment by guoweihua1982** [comment]
こちらで試験すると、Eclipse4.8でも問題ないようです。
不具合のER図をご提供いただけませんか？
